# Generated by Django 3.0.1 on 2020-03-22 06:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.BinaryField()),
                ('children', models.BooleanField()),
                ('role', models.CharField(choices=[('S', 'Student'), ('P', 'Profesor')], default='P', max_length=1)),
                ('available', models.BooleanField()),
                ('idUci', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal.person')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_guard', models.CharField(choices=[('S', 'Student'), ('P', 'Profesor')], default='P', max_length=1)),
                ('algorithm', models.CharField(max_length=200)),
                ('heuristic', models.IntegerField()),
                ('executor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.person')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
