# Generated by Django 3.0.1 on 2020-03-25 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteration',
            name='type_guard',
        ),
        migrations.AddField(
            model_name='iteration',
            name='date_end',
            field=models.DateField(default=datetime.date(2020, 3, 25)),
        ),
        migrations.AddField(
            model_name='iteration',
            name='date_start',
            field=models.DateField(default=datetime.date(2020, 3, 25)),
        ),
    ]
