# Generated by Django 3.0.1 on 2020-03-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20200326_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='date_start',
            field=models.DateField(),
        ),
    ]
