# Generated by Django 3.0.1 on 2020-03-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20200326_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteration',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iteration',
            name='type_guard',
            field=models.CharField(choices=[('S', 'Student'), ('P', 'Profesor')], default='P', max_length=1),
        ),
    ]
