# Generated by Django 3.0.1 on 2020-03-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_auto_20200326_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='number',
            field=models.IntegerField(),
        ),
    ]
