# Generated by Django 3.0.1 on 2020-04-22 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20200405_0223'),
        ('planning', '0019_auto_20200406_0316'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='parameters',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='type_guard',
        ),
        migrations.AddField(
            model_name='parameters',
            name='key',
            field=models.CharField(choices=[('alg_student', 'Algorithm Student'), ('alg_student', 'Algorithm Profesor'), ('guard', 'Type Guard'), ('date_start', 'Date Start')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parameters',
            name='value',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='executor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.Person'),
        ),
        migrations.AlterField(
            model_name='messagequeue',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='personal',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal.Person'),
        ),
    ]
