# Generated by Django 3.0.1 on 2020-03-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_remove_person_shift'),
        ('repoPlan', '0003_remove_shift_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='person',
            field=models.ManyToManyField(to='personal.Person'),
        ),
    ]
