# Generated by Django 3.0.1 on 2020-03-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repoPlan', '0003_remove_shift_person'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repoPlan.Shift'),
        ),
    ]
