# Generated by Django 3.0.1 on 2020-03-27 19:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('repoPlan', '0003_remove_shift_person'),
        ('personal', '0003_auto_20200327_1812'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='shift',
        ),
        migrations.AddField(
            model_name='person',
            name='shift',
            field=models.ManyToManyField(to='repoPlan.Shift'),
        ),
    ]
