# Generated by Django 3.0.1 on 2020-04-05 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_remove_person_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Uci',
            new_name='uci',
        ),
    ]
